[server]
browser = "default"
follow_symlink = false

[completion]
activate_on_typing = false

[save]
autosave_delay = 5000
format_on_save = true
autosave = "after_delay"

[keymap]
preset = "default"

[keymap.overrides]
"global.commandPalette" = "Cmd-Shift-p"
"global.showHelp" = "Cmd-Shift-h"

[display]
code_editor_font_size = 16
cell_output = "below"
default_width = "full"
theme = "system"
dataframes = "plain"

[runtime]
auto_instantiate = false
on_cell_change = "autorun"
auto_reload = "off"

[experimental]

[package_management]
manager = "uv"

[formatting]
line_length = 88

[snippets]
include_default_snippets = false
